### PR TITLE
Replace built in PropTypes from React core with stand-alone package

### PR DESCRIPTION
**Pull request by aesopwolf**
This should fix the warning `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.` and prepare us for the release of React 16.

### CODE REVIEW

**Comment by jsillitoe** [comment]
Thank you.  I'll merge it in as soon as I can get a few minutes

**Comment by manuelitox** [comment]
Hi @jsillitoe any news about this? thanks!

**Comment by tino-junge** [comment]
Will this be merged anytime soon, @jsillitoe ?

**Comment by jsillitoe** [comment]
Sorry for the delay.  Just merged in now

**Pull request merged**
