### PR TITLE
chore: adapt to react v15

### PR DESCRIPTION
**Pull request by zhuangya**

### CODE REVIEW

**Comment by zhuangya** [comment]
ref #26

**Comment by jsillitoe** [comment]
Thank you for this.  There were some conflicts with other pull requests so I included your changes manually.

**Comment by aesopwolf** [comment]
@jsillitoe would you mind publishing to npm? :)

**Comment by jsillitoe** [comment]
@aesopwolf I'll be publishing the updated version to npm tomorrow afternoon.  :)

**Comment by jsillitoe** [comment]
@aesopwolf The new version has been published.

**Pull request closed without merging**
