### PR TITLE
moves react and it's packages to peer deps and update build to use rollup instead of webpack

### PR DESCRIPTION
**Pull request by malbernaz**
First and foremost I'm really sorry for such a verbose PR.

This solves #55 by moving react, react-dom and prop-types to peer dependencies, avoiding conflicts with the versions of this packages installed by the dev.

And it solves #54 as well, by replacing webpack with rollup which is more suited for libraries than it's contender.

Hope you enjoy my effort... Your package is a life saver for me.

Thank you very much : )

### CODE REVIEW

**Comment by pelhage** [comment]
Our project's upgrade to React 16 has been blocked a bit due to `react-currency-input` having this issue, I believe. Would love to see this merged in!

screen shot 2017-10-20 at 10 55 39 am

**Comment by bendapkiewicz** [comment]
+1

**Comment by DesignMonkey** [comment]
+1

**Comment by malbernaz** [comment]
Thanks, mate!

**Comment by bvanderdrift** [comment]
+1

**Pull request merged**
